### ISSUE TITLE
PCB: remove unnecessary pull-up resistors

### ISSUE THREAD

**Issue by opatiny** [Hackuarium/bioreactor#28]
As shown in the image below, many pins of the DRV8811 are already pulled-up internally with 1MΩ resistors.

![pullups-drv8811](https://user-images.githubusercontent.com/17711389/84768775-139a5e00-afd5-11ea-9ef1-bafc8cd35043.png)

**Comment by andrescvargasr** [comment]
Deleted:

- R_{PD} (R35) pin ENABLEn (internally pull up) and connected to GND.
- R_{PU} (R37) pin SLEEPn (internally pull down) and connected to VCC.
- R_{PU} (R38) pin RESETn (internally pull up) and disconnected.

Added:

- C36 (100 n) to VMA.
- C36 (100 n) to VMB.
